### ISSUE TITLE
Improve the ADR bot notifications

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#10]
The emails now look like this:

> [ADR bot] Change in openedx/open-edx-proposals: Follow-on Implementation Strategy for OEP-45
> 
> A pull request has files you might be interested in.
>
> "Follow-on Implementation Strategy for OEP-45 " (https://github.com/openedx/open-edx-proposals/pull/144 by bderusha) against the openedx/open-edx-proposals repository (branch master) has been closed.
> 

The subject line should include "closed", and the body of the message should mention who closed it.

**Comment by hurtstotouchfire** [comment]
I was thinking this today actually -- could we reorder the information in the subject a bit? the most relevant parts seem to always be truncated out.

**Comment by hurtstotouchfire** [comment]
@nedbat do you know where the code for the bot lives or if it requires some sort of administrative access? I think if there is enough info in this issue to make it actionable we can probably get someone to do it.

**Comment by nedbat** [comment]
Details of the bot are here: https://openedx.atlassian.net/wiki/spaces/OPEN/pages/2286878789/ADR+Notification+bot (code, config, deploy)

**Comment by nedbat** [comment]
I updated the configuration of the bot (no code changes were needed).  Here's one old notification, and one new one:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/23789/155396788-ca20780b-f5ce-4a66-a852-bb4b1721df27.png">

**Comment by jristau1984** [comment]
I'm not saying we should change anything here, but I'm not sure we really solved a problem for anyone, just switched from one personal preference to another.  I don't see any benefit in the latter layout... Was this a widespread complaint?
