### ISSUE TITLE
Clarify which CLA should apply to the edx org

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#101]
Currently, before we accept external contributions into code repos, we check that the author has signed the Open edX Contributor License Agreement.  This is done for both the openedx GitHub organization, and the edx GitHub organization.

This is the individual agreement: https://openedx.org/wp-content/uploads/2022/01/tCRIL-Individual-CLA-12.10.21.pdf

tCRIL tells us that it makes no sense for 2U to check that agreement for contributions into the edx GitHub organization, because the agreement is explicitly about the openedx organization.  IANAL, but I don't see mention of any GitHub organization in the agreement.

How can we get an answer about what agreement authors should sign before being allowed to contribute code to repos in the edx GitHub organization?  Maybe it's this agreement, maybe it's a new one?

**Comment by nedbat** [comment]
I wrote to legal@edx.org today.

**Comment by nedbat** [comment]
Jenn gave me an update in Slack: https://twou.slack.com/archives/D04LKKGU9S8/p1674660655468989

Jennifer McGowan
  [10:30 AM](https://twou.slack.com/archives/D04LKKGU9S8/p1674660655468989)
Hi Ned - hope you're well. Thanks for your patience on the CLA question. I'm consulting with a couple of folks in the broader 2U legal department - hoping that Deputy GC, Lillian, can work with you on this and, generally, serve as a resource for IP-related questions relating to Open edX. Waiting on a response from her but will ping her tomorrow if I don't hear from her.


Ned Batchelder
  [10:31 AM](https://twou.slack.com/archives/D04LKKGU9S8/p1674660707135009)
ok, thanks for the update. I didn’t expect it would be a quick answer :smile:


Jennifer McGowan
  [10:40 AM](https://twou.slack.com/archives/D04LKKGU9S8/p1674661204851009)
edX legal team is short-staffed right now, and I've been pushing (for well over a year) to have clarity from broader legal team on how to support Open edX-related questions -- fundamental ones that should be front-of-mind as we move to a platform company!

**Comment by sarina** [comment]
@nedbat the agreement you linked doesn't explicitly mention the `openedx` organization, because we wanted to leave it open to cover additional organizations owned by tCRIL if needed. The important sentence you're overlooking is the first one:

> Thank you for your interest in the Open edX platform open source project being administered by The Center
for Reimagining Learning (the “Organization”). 

The `edx` org is not administered by tCRIL, thus, the `edx` org is not covered by this agreement.

**Comment by nedbat** [comment]
We decided it was simplest to have no CLA.  Contributions are not accepted into the edx GitHub organization.
