### ISSUE TITLE
Finalize GitHub user audit

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#102]

**Comment by nedbat** [comment]
George has chatted with IT: they can handle the quarterly audit

IT has a backlog of offboarding.  They should raise the priority of offboarding.  tCRIL could help automate with Zapier.

George will ask for a refresh of the data, since it is now March.

**Comment by nedbat** [comment]
Not finished, let's run a new report and do it again.

**Comment by nedbat** [comment]
If we need to keep doing this after this one, IT will be doing it.

**Comment by feanil** [comment]
@nedbat doing the audit with initial questions on our side was pretty costly, could we review and finish with the data at hand?

**Comment by nedbat** [comment]
@georgebabey where does this stand?

**Comment by georgebabey** [comment]
I met with @feanil today and we finalized this round. We'll do another in the June timeframe, with some enhanced tooling from Axim and bring in 2U IT to do the review. I believe we can close this ticket.
