### ISSUE TITLE
Establish procedure for making any private decoupled wiki content public

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#104]
Some wiki spaces in https://openedx.atlassian.net were kept by tCRIL during the decoupling, but made private because they could contain edX-specific information.  The spaces were kept for historical reference, and eventually, to be made public where applicable.

We need to establish a procedure for 2U and tCRIL review of spaces or pages.

Sarina notes:
> Wes had provided me with a service desk link, https://2u-internal.atlassian.net/servicedesk/customer/portal/37, to handle such requests. However, I cannot access this any more.

**Comment by sarina** [comment]
Thanks! Following

**Comment by nedbat** [comment]
Proposed process:

1. Axim identifies content they want to make public. It could be entire space(s), or sub-tree(s), or a list of pages.
1. Axim notifies 2U's Open Source Process working group to request a review.
   - The request is an issue on the [Open Source Process working group board](https://github.com/orgs/edx/projects/7/views/4).
   - The request includes a clear indication of which pages to review: the space(s), or sub-tree(s), or pages.
1. The Open Source Process working group will choose someone to assess the pages.  People might include Ned Batchelder, Ryan O'Connell, or Julie Davis.
1. The 2U people will review the pages and decide.
   - Assessment will include a review for protecting 2U business secrets.
   - They might OK the entire request, or select some pages to hold back.
   - 2U can work with the Axim requestor to review individual pages and decide together.
1. 2U adds a comment to the requesting issue with the decision.
1. Once Axim has the list of 2U-approved pages, Axim will make the pages public.

**Comment by nedbat** [comment]
The Axim runbook: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438903337/On-call+Playbooks#%E2%9C%8D%EF%B8%8F-Make-Private-Wiki-Content-Public

**Comment by nedbat** [comment]
This process is now in the 2U wiki: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/436306127/Review+process+for+historical+wiki+pages
