### ISSUE TITLE
Make PROD space content public

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#105]
As a specific instance of #104, the PROD space blog (https://openedx.atlassian.net/wiki/spaces/PROD/overview, then select Blog in the left-hand panel) has a lot of relevant content that would be useful for the community, and likely has no private information.

How do we make it public?

**Comment by sarina** [comment]
Thanks! Following

**Comment by nedbat** [comment]
@ProductRyan can you work with Sarina to take a look through the blog posts in the PROD space, and check that they are OK to make public?

**Comment by sarina** [comment]
@ProductRyan said to me already,

> do you know if these posts were public pre-acquisition and confluence transition? I thought that they were. If yes, I don't see any issue re-opening them

I don't know how to check if they were public.

**Comment by feanil** [comment]
You have to look at it page by page, to see what the page permissions are.  It looks like none of the pages over-wrote the space permissions.  I don't know if the space was previously open.   There aren't that many pages, it may make sense to just meet and go through them and unarchive any we're okay with making public and delete the rest.

**Comment by nedbat** [comment]
Ryan says, "if it was public before, it is ok to make public"

**Comment by feanil** [comment]
@nedbat unfortunately I don't know if the space was public before, do you know about that?

**Comment by sarina** [comment]
I think our other option is to evaluate page-by-page, correct? I can do that as we encounter relevant pages referenced in various documentation, but won't be able to be comprehensive about it

**Comment by nedbat** [comment]
Off the top of my head, I don't know if the space was public, or how to determine that.

**Comment by nedbat** [comment]
Here's my assessment of the pages in the PROD blog:

# Consider further

I'm not sure of these, either because I don't know if the feature is available to the community, or because of business stats in the pages:

- [Program &amp; Degree level Zoom Integration](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/16/3338371320)
- [Program &amp; Degree level Discussion Integrations](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/16/3244097606)
- [Bulk Email Tool Default Filter](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/11/12/3238232104/Bulk+Email+Tool+Default+Filter)
- [Course Authoring Import Messaging &amp; Validation](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/11/2900460148)
- [New Payments Experience (MFE)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/09/18/1055719790)
- [Proctoring Improvements: Proctortrack is Live!](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/07/22/1030946888)
- [A Mobile Year in Review: Mobile FY19 📱🌏📈😀](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/06/21/1021903234)
- [Enterprise: Recovery email for restoring account access](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/03/18/955416867/Enterprise%3A+Recovery+email+for+restoring+account+access)
- [Enterprise Admin Dashboard - Learner Data](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/13/807142181/Enterprise+Admin+Dashboard+-+Learner+Data)
- [edX Mobile Update 📱🌏📈😀 (July 2018 + FY18 Recap)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/07/10/791282164)

# Make public

These discuss features that are available to the community, and have no business information:

- [Discussions Moderation: Reasons for editing or closing content](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/04/27/3403776116/Discussions+Moderation%3A+Reasons+for+editing+or+closing+content)
- [New Text / HTML Editing Experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/04/21/3273556036)
- [The New ORAs Grading Experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/04/15/3401252933/The+New+ORAs+Grading+Experience)
- [Course-Level Zoom Integration](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/04/07/3389685804/Course-Level+Zoom+Integration)
- [New Discussions Experience - Educator Preview](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/03/31/3228631419/New+Discussions+Experience+-+Educator+Preview)
- [New Discussions Experience - edX Global Staff Preview](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/23/3316875400/New+Discussions+Experience+-+edX+Global+Staff+Preview)
- [Updated CourseGraph Tool](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/11/17/3241148440/Updated+CourseGraph+Tool)
- [Course App Configuration: Progress, Discussions, Teams, Notes, Calculator, Wiki, Custom Pages, Textbooks, Proctoring](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/10/26/3217391709/Course+App+Configuration%3A+Progress%2C+Discussions%2C+Teams%2C+Notes%2C+Calculator%2C+Wiki%2C+Custom+Pages%2C+Textbooks%2C+Proctoring)
- [Jump Navigation in Learning Sequence Experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/10/07/3196583970/Jump+Navigation+in+Learning+Sequence+Experience)
- [Open Response Assessments - Reusable Rubrics](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/10/01/3188129913/Open+Response+Assessments+-+Reusable+Rubrics)
- [Discussions: Configuration &amp; Setting Centralization](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/29/2903409320)
- [Learning MFE](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/25/2966290466/Learning+MFE)
- [Course Certificate Generation Logic Improvement](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/16/2914747544/Course+Certificate+Generation+Logic+Improvement)
- [Studio Course Listing Home Performance](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/02/25/2399732399/Studio+Course+Listing+Home+Performance)
- [Open Response Assessment - Educator &amp; Learner Updates](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/02/18/2362671610)
- [Python 3 - Assessments Upgrade (and Full Platform Upgrade)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/06/10/1526497329)
- [MicroBachelors Coaching Data Collection](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/05/07/1434157638/MicroBachelors+Coaching+Data+Collection)
- [Public Course Content Access Pilot  (T&amp;L / Open edX)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/04/23/1393623120)
- [Teaching and Learning:  Improved Authoring Speed](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/10/22/1061553361/Teaching+and+Learning%3A++Improved+Authoring+Speed)
- [Staff Graded Points ready for Fall](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/08/09/1041006661/Staff+Graded+Points+ready+for+Fall)
- [A New Look at Account Settings &amp; Performance 👀](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/06/21/1022132549)
- [A New Learner Profile: Reflection &amp; Development Speed  (Architecture Theme)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/05/15/1000408110)
- [edX Pattern Library: Paragon](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/05/13/998867381/edX+Pattern+Library%3A+Paragon)
- [Order History - New Micro Front End (Architecture Theme)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/04/26/992641473)
- [Sustaining &amp; Escalations: Expanded Language Support for Learning Experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/04/26/992641303)
- [Architecture: OAuth Scopes](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/10/807305448/Architecture%3A+OAuth+Scopes)
- [Authoring Efficiency: Files &amp; Uploads Results](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/07/805273758)
- [Transferrable Learner Records](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/03/803831933/Transferrable+Learner+Records)

# Keep private

These pages only apply to edx.org, or have too much business information to be public:

- [Mobile Apps Release 3.1](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/07/3316514832/Mobile+Apps+Release+3.1)
- [Organization-Level Feature Configuration Option](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/01/28/3319988426/Organization-Level+Feature+Configuration+Option)
- [Identity Verification (IDV) Changes](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/01/26/3315564727/Identity+Verification+%28IDV%29+Changes)
- [Interim Search Integration](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/01/25/3315302622/Interim+Search+Integration)
- [Product Tour](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/01/12/3302359049/Product+Tour)
- [One Step Registration](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/12/07/3266117765/One+Step+Registration)
- [Learner Demographics Collection - MicroBachelors](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/07/23/1663238145/Learner+Demographics+Collection+-+MicroBachelors)
- [[Product Pulse] Program Data Reports - Full rollout update](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/06/19/1553859326)
- [[Product Pulse] Program Data Reports v1 Pilot - Launched](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/04/06/1337460030)
- [Institutional &amp; Course Data Researcher Roles](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2020/02/05/1184170254)
- [Product Pulse - Integrations for Master's programs](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/09/16/1054737167/Product+Pulse+-+Integrations+for+Master%27s+programs)
- [Course About Page Improvements](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/08/05/1035010250/Course+About+Page+Improvements)
- [Access Management - Assigning Enterprise Roles](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/05/22/1002799138/Access+Management+-+Assigning+Enterprise+Roles)
- [Product Pulse: Master's Theme - Enhanced lead management v1](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/03/08/953156688/Product+Pulse%3A+Master%27s+Theme+-+Enhanced+lead+management+v1)
- [Discovery: Computer Science pages in new experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/11/27/917962801/Discovery%3A+Computer+Science+pages+in+new+experience)
- [Discovery: Data Science Subject &amp; Course About Pg Launch](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/09/27/851935415)
- [Revenue Test Launch: Content Gating v2](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/07/805470643/Revenue+Test+Launch%3A+Content+Gating+v2)
- [Revenue: Track Selection and Enrollment Flow Test Results](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/07/19/796819550/Revenue%3A+Track+Selection+and+Enrollment+Flow+Test+Results)
- [Revenue: Required Support Fee Test Results](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/07/16/793969259/Revenue%3A+Required+Support+Fee+Test+Results)
- [Revenue Test Launch: Verified-Only Programs](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/07/03/787546167/Revenue+Test+Launch%3A+Verified-Only+Programs)
- [Master's Phase 1 released](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/06/29/785580168/Master%27s+Phase+1+released)
- [Customer Request Intake Process](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/06/29/785383560/Customer+Request+Intake+Process)
- [EdX &amp; GDPR: Our adherence to new data regulations](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/06/19/769687849)
- [Revenue Squad: Optional Support Fee Test Results](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/06/14/767033582/Revenue+Squad%3A+Optional+Support+Fee+Test+Results)
- [Revenue Squad: Tests on enrollment and track selection experience](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/05/29/749076547/Revenue+Squad%3A+Tests+on+enrollment+and+track+selection+experience)
- [Product Development at edX](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/05/17/734953574/Product+Development+at+edX)

**Comment by nedbat** [comment]
@ProductRyan Can you take a look at the 10 "Consider Further" pages?

**Comment by sarina** [comment]
Methodology: For the pages to make open, I'm moving them from the private PROD space to the public OEPM space (ex: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/02/23/3316875400/New+Discussions+Experience+-+edX+Global+Staff+Preview?moved=true) 

I'm moving the ones to make public, then I'll review the maybes and see if there's anything that seems like we might particularly want

**Comment by sarina** [comment]
@jmakowski1123 do you think any of these product blog posts should be public? I've left my comments here:

- I am not sure: [Program & Degree level Zoom Integration](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/16/3338371320)
- I don't think so; this is publicly available now [Program & Degree level Discussion Integrations](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2022/02/16/3244097606)

- This has a throwaway line that open edx people can configure this if they need. Perhaps that's enough for us to want the post? You could argue it could be scrubbed of references like "Braze" [Bulk Email Tool Default Filter](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/11/12/3238232104/Bulk+Email+Tool+Default+Filter)
- Yes but remove support ticket data [Course Authoring Import Messaging & Validation](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/11/2900460148)
- No [New Payments Experience (MFE)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/09/18/1055719790)
- I'm not sure if the community uses this [Proctoring Improvements: Proctortrack is Live!](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/07/22/1030946888)
- I think this is too much edX data to release [A Mobile Year in Review: Mobile FY19 📱🌏📈😀](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/06/21/1021903234)
- I don't think this is worth making public unless this is a feature that is rolled into the main platform (how many community members use Enterprise?) [Enterprise: Recovery email for restoring account access](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2019/03/18/955416867/Enterprise%3A+Recovery+email+for+restoring+account+access)
- Same as above, how many use enterprise? [Enterprise Admin Dashboard - Learner Data](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/08/13/807142181/Enterprise+Admin+Dashboard+-+Learner+Data)
- Same as above, is just a bunch of edX data. [edX Mobile Update 📱🌏📈😀 (July 2018 + FY18 Recap)](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2018/07/10/791282164)

**Comment by nedbat** [comment]
Sarina and I edited [Course Authoring Import Messaging & Validation](https://openedx.atlassian.net/wiki/spaces/PROD/blog/2021/06/11/2900460148) to remove edX-specific details, and made it public.

The rest of the Consider Further pages were left private.
