### ISSUE TITLE
Improve 2U Open edX On/Off boarding Process

### ISSUE THREAD

**Issue by feanil** [edx/open-source-process-wg#111]
The current process for on-boarding is very last minute and can sometime result in the engineering not having the relevant access as quickly as 2U usually expects.

The current off-boarding process is quite opaque and it's not clear that Axim is receiving all the off-boarding tickets that we expect.

On the Axim side, Salesforce is the system of record and Axim will create contact records for all staff that are associated with an account record representing 2U.

They need to know the following:

- First Name
- Last Name
- Email Address
- GitHub username
- Open edX Slack username -- nice-to-have
- Start date
- End date, if applicable
- Teams to add the person to

**Comment by nedbat** [comment]
Also: #117

**Comment by nedbat** [comment]
Off-boarding seems to happen in slow batches, and should be sped up.

**Comment by jristau1984** [comment]
@feanil is Axim still seeing these issues?  It seems that maybe things have gotten a little better recently, so I want to see if this is still needed.

**Comment by feanil** [comment]
Yea, I think this can be closed now, the process seems to have improved  in timeliness and we'll be doing regular audits as a backstop.
