### ISSUE TITLE
Make certain Sustaining Wiki Docs Public

### ISSUE THREAD

**Issue by feanil** [edx/open-source-process-wg#113]
Urgency: Med/Low

On the Open edX wiki, we cleaned up a lot of private Sustaining team documents, but found that some of them would be useful for the rest of the community.  We would like to make those documents public.

Per the agreement between 2U and Axim, we need review and approval from someone on the 2U side before we can make the content public.

The private content currently lives at https://openedx.atlassian.net/wiki/spaces/SUST/pages/135102673/Team+Internal+Documents

I've removed anything that seems like it shouldn't be made public and want to open up everything that's left.

#### Proposed Process for this ticket

1. Please provide me with the name/atlassian account email of someone who can review the documents and approve the change in visibility.
2. I give them permission to see these private documents.
3. They review, update and provide feedback on the documents until we arrive at a place where we are agreed that anything that is left is safe to be made public.
4. I update the confluence permissions so the content is public.

**Comment by nedbat** [comment]
I will take a look at the docs and choose the real decider (which could be me).

**Comment by feanil** [comment]
@nedbat I've added you to the page, you should be able to see it and all child pages.

**Comment by nedbat** [comment]
I've looked through it, we should discuss.  Either specially, or at a regular 1:1.

**Comment by nedbat** [comment]
I agree that all the requested pages can be made public.

**Comment by nedbat** [comment]
I agree that all the requested pages can be made public.

**Comment by feanil** [comment]
They've been made public and moved here: They've been made public here: https://openedx.atlassian.net/wiki/spaces/AC/pages/34013353/Debugging+Docs
