### ISSUE TITLE
GitHub teams spring cleaning

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#115]
Axim has a spreadsheet of teams: https://docs.google.com/spreadsheets/d/1nDWMTbmDHyrwWJsSsyr6d6Bx97IKAoKpm5mSVjRj108/edit#gid=188213499

We need to provide information about teams to keep, so that Axim can clean up the teams in the openedx GitHub organization.

This is due by June 1.

**Comment by nedbat** [comment]
I sent an email to eng-mgrs today.

**Comment by e0d** [comment]
I think this is what happened this morning?  Feanil removed folks from a list provided by @georgebabey

**Comment by feanil** [comment]
That was for users, there is also a teams audit that Kyle, Sarina and Brian S did recently, this ticket pertains to that audit of Github Teams and not the audit of github users.

**Comment by nedbat** [comment]
Kyle finished the teams cleanup yesterday.
