### ISSUE TITLE
2U Engineer and Eng Manager Open Source Orientation

### ISSUE THREAD

**Issue by feanil** [edx/open-source-process-wg#130]
I recently ran into a situation where a 2U eng lead was unaware of how the 2U slack is connected to the Open edX slack and how [CCs outside the company might be attempting to communicate](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2800255156/Communication+Between+Coding+CCs+and+2U+edX+Engineers) with him and his team.

I wonder if there could be some sort of synchronous 30-min orientation for new technology hires that would orient them to the community and how comms work and where contributions might come from.  This information may be written down but perhaps not being read?

**Comment by nedbat** [comment]
I suspect there are actual fixes to communication channels, and to the information written about those channels, that needs to happen.

**Comment by nedbat** [comment]
@feanil btw, why did you ask for synchronous specifically?

**Comment by feanil** [comment]
Mostly because I believe there is documentation on this but it might not be presented to people at the right time or not being consumed.  I think the real desire would be confirmation that people did indeed consume this information.
