### ISSUE TITLE
Document and agree upon points of contact with tCRIL and 2U/edx

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#16]
> In trying to describe the overall sense of opaqueness, I've had trouble conveying how little I understand and how little seems to be common knowledge among 2U engineers. This is a straw-man documentation request and possibly the most important thing this can provide is to make concrete the unknown unknowns and help expose blind spots for those already in-the-know. I do think this would be a useful documentation entry point though. This would be publicly available information, not some internal agreement between managers at the two organizations.
>   -- @hurtstotouchfire 

## Acceptance criteria

- A single page which describes avenues of contact and what they are for.
- Doc should be suitable for inclusion in onboarding documentation within 2U.
- Does not need to set policies or detail workflows & should link out to other docs as much as possible.
- Should assume very little prior knowledge of the relationship between the orgs, the former roles played by tCRIL staff, and precedents for ownership of different parties involved.
- May need discernment to separate from actual workflow docs (e.g. PR merge policies)

Use cases / personas:

- 2U/edx staff who have no idea what's going on between the two orgs (this is a common reality)
- New hires who are familiar with common OSS practices but not familiar with the background between the orgs (e.g. how are we temporarily or indefinitely blurring the role of "maintainer")
- New hires who know little about open source but are interested in getting involved

## Initial questions

- What docs already cover this sort of information?
- What docs can we link to for the history / story of the decoupling?
- What does tCRIL think is common knowledge?
- What work may be necessary by 2U leadership to ensure that tCRIL can broadcast information and that it will actually get read / looked at? (for instance, right now even though much of the tCRIL decoupling documentation is public on github, most engineers have no idea that it exists)

### Open edX Slack

- Anyone in the public who signs up
- Includes whole tCRIL staff
- Includes many but not all 2U/edX staff
- Also has shared channels with internal 2U / edX slack

### Tutor adoption project
@feanil noted this as a point of contact and I agree but can't totally say why. Is every open source project 2U is involved in a point of contact with tCRIL? Would it be only projects that tCRIL has a significant role in? Is there actually representation from tCRIL in the working group?

### Github artifacts
Committed ADRs / OEPs, Issues, PRs, wikis... many people put information in these places but they are really only a point of contact if someone else reads them. Can we solicit review from tCRIL? How does that work? Is it assumed that tCRIL monitors some things?

**Comment by hurtstotouchfire** [comment]
@muselesscreator

**Comment by nedbat** [comment]
My hope is that the points of contact are too numerous to list.  Every blended project is a point of contact. Every working group is.  As you asked, "is every open source project 2U is involved in a point of contact with tCRIL?"

Maybe we need some clarification about what points of contact are worthy of being listed?

**Comment by sarina** [comment]
We have a [team page in Confluence](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3241640370/tCRIL+Engineering+Team) that's pretty lean, not out of withholding information but more of a "hey we should slap something together real fast so we have a wiki presence"

It would be helpful I think if you wanted to make a subpage in that space, formatted the way you want, with the questions you want answered populated on it. The tCRIL team is happy to go in and create the content.

**Comment by hurtstotouchfire** [comment]
@nedbat I agree that they should be too numerous to list but I think my point is that right now they are not discoverable and for people not in-the-know, they are invisible. So an incomplete list (preferably intentionally so, with some definition as to what goes on there vs gets left off) would be an improvement.

I also talked with @ormsbee about the idea of tCRIL holding office hours, which is a good discoverability fallback. In my first couple months at 2U/edx I spent (and still do) a lot of time spinning my wheels trying to find the right people to ask about something, and Arch Hour has been a great shortcut that has gotten me what I needed several times.

The other thing that I think cannot be underestimated is just showcasing for people the general shape of the overlap. There are a lot of people right now who aren't getting updates on tCRIL/2U collaboration and may not even know that any projects are happening. We can make announcements and make noise about particular projects in slack, but a broad menu will provide a different perspective.

**Comment by hurtstotouchfire** [comment]
Just some updates:

- Started drafting [a thing on confluence](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3330736740/DRAFT+--+Contact+us+Work+with+us) based on Sarina's suggestion, but felt unclear on who the audience was and who the owner / voice should be, and got blocked.
- Had a few good conversations with OSP wg folks and decided that I want to focus on **ways that 2U engineers can reach out to get plugged in with open source work**. A sort of sub-goal there is also to make it clearer how 2U engineers should interact with tCRIL, but I think that is a vaguer question.
- My current goal for a doc page:
  - should be an **entry point** primarily, linking to other things
  - should focus on contexts which offer **2-way communication** (e.g. slack, actual scheduled meetings, office hours) and not information firehoses / passive communication / readthedocs type stuff. This rules out some github artifacts (one class of communication mentioned above) but still includes PR reviews, issue commenting, etc.
  - should articulate some of the **communication-focused groups** if they are joinable, so a link-out to closely related working groups like OSP WG and the Product working group. I'm on the fence as to whether open source collaborations (like Tutor) should be on the same page, I think probably not but maybe we link to them.

**Comment by jristau1984** [comment]
I think there is a difference between required, continual communication channels and feedback loops with collaborators or stakeholders for a project.  If this is trying to identify the specific and forced connection points between two organizations, then it should be scoped specifically to that (i.e. the Product Sync, Architecture Group, TOC, etc)

**Comment by nedbat** [comment]
I started an outline of what I think we might be looking for? https://openedx.atlassian.net/wiki/spaces/~ned/pages/3354493025/Open+edX+Community+overview

**Comment by hurtstotouchfire** [comment]
I think we should archive this as "too big" and make separate issues for moving the actually completable pieces. Maybe also some other blocking pieces could be represented, such as OSPwg getting a copy of the decoupling contract.
