### ISSUE TITLE
Improve edX onboarding to CLA database

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#2]
The Contributor License Agreement database is a list of everyone who is legally permitted to contribute code to Open edX repos.  That database is now managed by tCRIL in Salesforce.  edX onboarding has a few friction points that make that process a little bumpy.  Smooth those out to fully automate it.

**Comment by natabene** [comment]
Can you remind me which friction point this is about?

**Comment by nedbat** [comment]
On Jan 26, @e0d said, 

> There seems to be some documentation telling individual devs to send an email after they start with their GitHub details.
> 
> It can't work this way.
> 
> We need positive confirmation from HR or similar that this person should be covered under the entity CLA.
> 
> Prior to this we have:
> 
> [...Image of onboarding email from 2U omitted...]
> 
> This doesn't provide their GH username and indicates that there is not certainty of the need and that the manager should confirm.
> 
> I doubt the manager knows this -- well they are cc'd on the email.
> 
> I'd really like the following to be true:
> - We collect GH username with a signed offer letter.
> - We get a single, definitive message in advance of start with all the required details.

**Comment by natabene** [comment]
Talked to HR, they will try to collect usernames before employees start. Once we confirm it is happening as expected, I will close this issue.

**Comment by natabene** [comment]
I have not heard any complaints from Ed, so I assume it is working well and we can close.

**Comment by nedbat** [comment]
> I was unable to update the documentation in confluence

Can we help with that? Where, and what prevented you?

**Comment by jristau1984** [comment]
I can't find the specific place anymore, and the page looks to have had content updated recently to refer to some 2U tools.  I dont see a place referring to the OpenEdx organization request at all though... @natabene may know better where it specifically is located.

**Comment by natabene** [comment]
@jristau1984 Did you mean: [this page](https://openedx.atlassian.net/wiki/spaces/ENG/pages/12550298/Developer+Onboarding) ?

**Comment by jristau1984** [comment]
Yes.

**Comment by natabene** [comment]
I just created a comment on that page asking IT about this.

**Comment by natabene** [comment]
All seems going well now, no complaints from any party about the onboarding process. Closing this.
