### ISSUE TITLE
OEP-55: Paragon use case

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#30]
Disclaimer: super super drafty

We're going to be thinking through several use cases for rolling out OEP-55. Paragon has some interesting features but may be complicated enough to not be a good pilot.
_________________________________________________________________________
Initial thoughts:

I think some precedents and best practices may come out of this, but since the Paragon library is already hitting a lot of issues with separating the private / public aspects of their work, I've been talking with @adamstankiewicz about this as a model for how we might encapsulate business concerns and processes while making public / open source concerns as discoverable and easily maintained as possible.

Some interesting features of this use-case:

- Paragon is arguably our most independent / reusable library so it could conceivably have a user base encompassing non-Open-edX users.
- We support themes, and currently the edX brand theme is public, but in the future it could conceivably need to include private concerns from 2U.

**Comment by adamstankiewicz** [comment]
> Paragon is arguably our most independent / reusable library so it could conceivably have a user base encompassing non-Open-edX users.

It would be interesting to try to gauge if there are any consumers of Paragon outside of the Open edX ecosystem (e.g., IIRC the majority of the [Paragon dependents](https://github.com/openedx/paragon/network/dependents) are forked of Open edX repositories).

I think a decision would also need to be made on whether we want Paragon to be a general purpose design system / component library or one specifically intended for use cases within Open edX (e.g., what value would be getting if Paragon is more general purpose and truly agnostic from Open edX). There are likely advantages/tradeoffs to both options.

> We support themes, and currently the edX brand theme is public, but in the future it could conceivably need to include private concerns from 2U.

Just to add some color here, Paragon indeed supports theming today. By default, Paragon ships with a core theme. Consumers don't need to do anything extra if they don't plan on using an external theme.

If using an external theme, we rely on an `@edx/brand` NPM alias today, where a separate Paragon theme is installed from either `@edx/brand-openedx` (no theme overrides) or `@edx/brand-edx.org` (has theme overrides) but will be imported through an `@edx/brand` NPM alias, e.g.:

```json
{
  "dependencies": {
    "@edx/brand": "npm:@edx/brand-edx.org@2"
  }
```

This allows us to use `@edx/brand-openedx` during development but replace the theme during our build pipelines by installing the `@edx/brand-edx.org` theme to the `@edx/brand` NPM alias instead.

Paragon itself does not read from @edx/brand directly; instead it relies on the consumer to import their brand overrides [as documented](https://paragon-openedx.netlify.app/guides/installation-and-usage#scss-foundation), e.g.:

```scss
@import "@edx/brand/paragon/fonts.scss";
@import "@edx/brand/paragon/variables.scss";
// Import the Paragon core after setting brand-themed variables.
@import "@edx/paragon/scss/core/core.scss";
// Import brand overrides after the Paragon core.
@import "@edx/brand/paragon/overrides.scss";
```

If we eventually decide to make the 2U/edX theme private, we'd want to have the Github repo for the theme be private as well the published NPM package. Neither of these changes would have an impact on Paragon.

**Comment by hurtstotouchfire** [comment]
I'm closing this for now in favor of larger conversations coming out of https://github.com/edx/open-source-process-wg/issues/32
