### ISSUE TITLE
OEP-55 Rollout - Maintainers

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#31]
## Overview
The [maintainers OEP](https://github.com/openedx/open-edx-proposals/pull/290) merged with a status of provisional back in May. [Defining maintainership](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426418790/Maintainership+of+Open+edX+Repos) will be an ongoing process, and we are currently starting a [pilot](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Bootstrapping+Maintainership) with a subset of repos to get basic infrastructure in place. 

## Rollout objectives

- [ ] - The set of repos included in Open edX is known and clearly enumerated via some single source of truth
    - OEP-57 - What is the set of repos? https://github.com/openedx/open-edx-proposals/pull/312/
- [ ] - Maintainers are declared for each of the components of Open edX (and have responded accepting the responsibilities)
    - Single source of truth: [Backstage](https://open-edx-backstage.herokuapp.com)
    - [Repo Maintainer List working doc](https://docs.google.com/spreadsheets/d/1tI5OPMjnhL6obzynuAUURLjOSN72QWCkHSXGGoFLMG8/edit#gid=819569654) (not public but request access or ask @hurtstotouchfire )
- [ ] - A system is in place for providing maintainers with quant / qual feedback on their progress "maintaining project standards"
  - [Requirements for public repos](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1475084709/Requirements+for+public+repos)
- [x] - Scrum of scrums is meeting
  - Pilot maintainers SOS on Aug 10th!

## Contacts

- @hurtstotouchfire
- @jristau1984 
- @jmbowman 

## Work in Progress
- https://github.com/openedx/open-edx-proposals/pull/357 - Maintainer transfer process OEP
- Cleaning up [DoneXBlock](https://github.com/openedx/DoneXBlock) README to use as an example for new README standards.
- Starting to add Backstage config files to identify code owners (see [example config for Credentials](https://github.com/openedx/credentials/pull/1705)).
- [Evolving standards for public repos](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1475084709/Requirements+for+public+repos)

## Status Updates
- 7/27 - Finalized maintainer contact people, started openedx slack channel (#maintainers-pilot), scheduled first Scrum of Scrums for 8/10 at 9AM eastern time. 
- 7/20 - Added [credentials](https://github.com/openedx/credentials) to the pilot.
- 6/21 - Repos in scope for SOX compliance also included in the pilot.
- 6/1 - tCRIL / 2U planning meeting for pilots. Tentative list of pilot repos chosen.
- 5/13 - [OEP-55](https://github.com/openedx/open-edx-proposals/pull/290) merges with provisional status.
- 4/21 - OEP-55 itself is still in draft, but should be merged soon with at least a provisional status. I've outlined some ["phase 0" steps](https://github.com/edx/open-source-process-wg/issues/34), some of which feel like they are blocking a robust pilot project, and others are just for reducing the pilot problem space. I'll be following up on those tasks.
- 4/14 - Revised this issue to be a parent ticket with an overall outline, some updates, and links out to sub-tasks.
- 3/24 - OSPwg starts a task force to decide on concrete actions for 2U to adopt OEP-55. Adopted at OSP WG [3/34 meeting](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19466682/2022-03-24+OSPwg+Meeting+notes). 

## Reference
- [OEP-55 - Read The Docs](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html)
- [Bootstrapping Maintainership - Open edX wiki](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Bootstrapping+Maintainership) - public status and documentation page for the pilot & other bootstrapping work

**Comment by sarina** [comment]
I want to capture @hurtstotouchfire comments on OEP-55 before the diff goes away:

---------------------

My $0.02 would be Provisional but with a concrete timeline / set of objectives for what constitutes "implemented". That might be:

* Set of repos included in Open edX is known and clearly enumerated via some single source of truth
* Maintainers are declared for each of the components of Open edX (and have responded accepting the responsibilities)
* A system is in place for providing maintainers with quant / qual feedback on their progress "maintaining project standards"
* Scrum of scrums is meeting

**Comment by sarina** [comment]
I made this wiki section to help us document pilot phases & timelines. Could we ensure that documentation is put here? https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426418790/Maintainership+of+Open+edX+Repos

**Comment by nedbat** [comment]
tCRIL had a kick-off with ..... they are doing it.

**Comment by hurtstotouchfire** [comment]
@nedbat fyi, I capriciously decided to keep this as the primary tracking ticket and I'm closing the other phases tickets. I may end up making new child tickets based on the pilot now that it's in motion.

**Comment by hurtstotouchfire** [comment]
TODO:
Add a sentence or two explaining what this OEP would do for 2U, making it clear that this should be a business priority. Maybe wordsmith this slack message I sent Yaro:

>For actively maintained repos owned by 2u, it's not going to be a huge change
This is more about formalizing the edX concept of ownership across different community members
So in the long term, this should help us offload some of our current maintenance burden and get more out of the open source community

**Comment by nedbat** [comment]
We discussed on Sep 7th that this ticket needs to be split.

**Comment by hurtstotouchfire** [comment]
I'm moving this to a page in our internal wiki: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/179306499/Initiative+Maintainership+Pilot
From there I will de-dupe with the public wiki page: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Maintainership+Pilot
And any future task tracking will happen on future issues, the next of which is https://github.com/edx/open-source-process-wg/issues/31
