### ISSUE TITLE
OEP-55 - Phase 1: Pilots

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#32]
We'd like to do some gap analysis in preparation for [OEP-55](https://github.com/openedx/open-edx-proposals/pull/290) and ideally pilot the new maintainer structure with a few repos.

## Use cases
All of these cases assume that we're currently maintaining the repo. Are there any that we don't maintain but might have to take on?

1. Repos we currently maintain & will keep
    a. Maintenance is already close to goal
    b. Close large maintenance gap
2. Transition to new maintainer
    a. Still in use by 2U / edx.org
    b. Formerly used by 2U / edx.org, now deprecated or unused
    c. Not used or used historically by functions now moved to tCRIL (e.g. CC program, Open edX conference, etc)
3. Only used by us / not part of Open edX
    a. keep public on 2U-owned org
    b. transition to private

### 1. Keep & maintain
These would be the primary cases where we need to sort out what OEP-55 compliance looks like for us.

- TNL: [edx/frontend-lib-content-components](https://github.com/edx/frontend-lib-content-components) - This might be a good straightforward case.
- Paragon (see [Issue 30](https://github.com/edx/open-source-process-wg/issues/30)) - This is a more complex case

### 2. Transition to new maintainer

- [openedx/xblock-drag-and-drop-v2](https://github.com/openedx/xblock-drag-and-drop-v2)
- [openedx/xblock-adventure](https://github.com/openedx/xblock-adventure)
- [openedx/xblock-image-explorer](https://github.com/openedx/xblock-image-explorer)
- [openedx/xblock-google-drive](https://github.com/openedx/xblock-google-drive)
- [openedx/blockstore](https://github.com/openedx/blockstore) - developed by OpenCraft with Dave Ormsbee (now at tCRIL). Not used by 2U / edx.org?

### 3. Only used by us
As far as we know, anything that needs to be private for business reasons is already private, so what might we want to make private for other reasons? Is there a model for 2U-owned open source that (in theory) does not need to comply with OEP-55?

**Comment by ashultz0** [comment]
https://github.com/openedx/edx-analytics-pipeline is a weird case but might be interesting.

2U will stop running any of this code this month. We know some partners (opencraft certainly, maybe others) still use it. The sad wrinkle is no one actually loves it or probably even likes it.
