### ISSUE TITLE
OEP-55 - Phase 0: Orientation & definitions

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#34]
### Phase 0: Orientation & definitions

- [x] Check in with tCRIL about source of truth for the presumably evolving "project standards"
- [ ] ~Solicit broad feedback within 2U about peoples interpretations about what this specifically means for their repos (Arch hour? OC Arch WG? Ask eng managers to bring up?)~
- [x] Transfer ownership of (or just remove from spreadsheet) any repos that don't make sense for us to maintain
- [x] Shift & rebalance ownership between squads to address workload issues and consolidate spheres of ownership

**Comment by hurtstotouchfire** [comment]
I probably need to articulate the phases on some parent issue (likely https://github.com/edx/open-source-process-wg/issues/31) and then make each of these issues for 1 phase. This is supposed to be the Phase 0 ticket, and hence this is the first time I've actually articulated possible tasks there. This all feels like vagueness blocking the pilots though.

**Comment by nedbat** [comment]
This is what we did with tCRIL to make the pilot list of repos.

**Comment by hurtstotouchfire** [comment]
The moving around of repo ownership is still in progress but the rest of this will be tracked via the main OEP-55 Pilot ticket, #31
