### ISSUE TITLE
Charter: clarify the purpose and role of the Open Source Process working group

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#37]

**Comment by nedbat** [comment]
I've added a [Charter section in the working group home page](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19467639/Open+Source+Process+Working+Group#Charter).   I'm sure there is more to say.  What questions or gray areas do people see?

**Comment by nedbat** [comment]
A (2U-private) working document: https://docs.google.com/document/d/1BMPded6v5MxOHACMadlsjgHCQ_w8cfOayNgho5aI00U/edit#

**Comment by jristau1984** [comment]
This was reviewed and ratified in today's OSPWG sync.

**Comment by nedbat** [comment]
Updated on https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19467639/Open+Source+Process+Working+Group
