### ISSUE TITLE
Write a vision/northstar for 2U participation in the Open edX ecosystem

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#38]
- Should be less concrete than a measurable goal like 50% contributions
- Outline key principles like equity, transparency, accessibility alongside some "stories" of what those mean.
- Start with stories and extract principles? (e.g. push-pull-all convo allowed us to extract equity vs equality)

**Comment by pshiu** [comment]
Working notes in progress at: https://docs.google.com/document/d/1TrdgYW6-i0RguQO9CJf5WZvABtfABx6pMrrWpxIvBIA/edit?usp=sharing

**Comment by nedbat** [comment]
[Grooming] we need to see where this is headed, and decide what to do with it.

**Comment by nedbat** [comment]
This is as done as it's going to get.
