### ISSUE TITLE
Enumerate 2U collaboration needs

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#40]
This is part of identifying how to reach equity among community members.  From https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19467068/2022-05-05+OSPwg+Meeting+notes

**Comment by jristau1984** [comment]
@nedbat I believe that the docs @jmbowman have recently produced solve most if not all of the goals of this ticket.  Can you confirm if that is true or if there are outstanding items?
