### ISSUE TITLE
Sign up some 2U non-tech contributors

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#44]
tCRIL has a Non-Technical Contributor entity agreement.  Get this approved by 2U legal.  tCRIL will then manage the list of people covered by the agreement.

**Comment by hurtstotouchfire** [comment]
This may also cover course authorship

**Comment by nedbat** [comment]
This is the Entity Non-Technical Contribution Agreement:

[entity non technical contribution agreement.pdf](https://github.com/edx/open-source-process-wg/files/9192718/entity.non.technical.contribution.agreement.pdf)

NOPE: updated doc is below.

**Comment by nedbat** [comment]
I've written to edX legal asking how to proceed.

**Comment by hurtstotouchfire** [comment]
FYI I think Ashley may be a good contact here now that he's joining the TOC. I also mentioned the blocking issue with course authorship to 2U's accessibility director Kevin Blemel. I could intro you in the 2U slack maybe?

**Comment by nedbat** [comment]
I talked with Jenn McGowan this morning. She is continuing to make progress on this, and will be talking to Ashley as the likely "business owner" for the non-technical contribution process.

**Comment by jristau1984** [comment]
@nedbat are you aware if this follow up happened, and if there is approval on the agreement?

**Comment by nedbat** [comment]
I have heard nothing more.

**Comment by nedbat** [comment]
Latest non-technical entity agreement (Sarina gave me this from docusign)
[Open edX NTC Program Agreement - Entity (4.1.23).docx.pdf](https://github.com/edx/open-source-process-wg/files/11728025/Open.edX.NTC.Program.Agreement.-.Entity.4.1.23.docx.pdf)

**Comment by nedbat** [comment]
If we need motivation for the importance of non-code contributions: https://github.com/readme/featured/open-source-non-code-contributions

**Comment by sarina** [comment]
Sounds like we have a few courses blocked on this - an a11y course (Kelly) and a Frontend course (@arbrandes ) - along with contributions to the in-progress Intro to Dev course. Just noting that the list is growing.

**Comment by nedbat** [comment]
Ryan O'Connell has agreed to be the 2U business owner.  I've written to 2U Legal to get the process started again.

**Comment by sarina** [comment]
Excellent news! thanks Ryan!!

**Comment by nedbat** [comment]
I think we have everything we need. I'm working with 2U Legal to get it signed.  Our proposal is: everyone covered by the technical agreement will automatically be covered by the non-technical agreement.  If someone not covered by the tech agreement wants to be covered as non-tech, we'll write an Axim ticket to add them to the list.

**Comment by nedbat** [comment]
I pinged Lillian today.

**Comment by nedbat** [comment]
I wrote this wiki page for details: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/591560761/Non-Technical+contributions

Aaron McCullough signed the agreement today.

**Comment by sarina** [comment]
omg! yay!
