### ISSUE TITLE
Decide if we need a forking strategy for edx-platform

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#6]
edx-platform is where the community wants to make changes, and also where edX business is centered.  Do we need an edx fork of edx-platform? How would we manage it?

My suggestion was to use a fork so that we could control when community changes were deployed.  We'd auto-push edX changes from the edx repo to the openedx repo immediately, but pull openedx changes down once per day so that we could monitor the deploy.  My thoughts were on this page: https://2u-internal.atlassian.net/wiki/spaces/~ned/pages/28049550/DevX+evolution

**Comment by hurtstotouchfire** [comment]
Is there more up to date documentation on this somewhere? I would assume tCRIL folks have a plan?

**Comment by nedbat** [comment]
There isn't a more up-to-date page, and I think it will be edX's decision whether to fork or not.  That might be heavily influenced by what tCRIL wants to do with contribution dynamics.

**Comment by sarina** [comment]
We definitely don't have a plan for what 2U does with its own dev process. We are strongly invested, though, in making sure your changes make it into the openedx repos at a consistent, up to date pace, and we are here for brainstorming if you want.

In general, I don't think tCRIL wants to be in the business of dictating a plan to any community member, but yeah happy to work together on problems!

**Comment by nedbat** [comment]
We definitely need a through-through understood consensus about when/where/why to fork a repo.  Getting this written is in #77.
