### ISSUE TITLE
OEP-56 Rollout - Architectural Processes

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#60]
### Overview
[OEP-56](https://github.com/openedx/open-edx-proposals/pull/305) merged with a status of Provisional on 3/28/22.

From the wiki page, circa 7/29/22
> In the short term, this body will act as a sort of manual switchboard to find the domain experts and stakeholders needed to have the architectural discussions described by OEP-56. If your team is considering a change that will have cross-team impact, you will be able to bring your idea as an agenda item to this working group. 

## Reference

- [OEP-56 - Read the Docs](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0056-proc-architectural-advisory-process.html#) 
- [New Working Group Proposal: Architecture Coordination](https://discuss.openedx.org/t/new-working-group-proposal-architecture-coordination/7786) - original Discourse thread
- [Architecture Coordination Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3490840587/Architecture+Coordination+Working+Group) - Main wiki page

**Comment by davidjoy** [comment]
Dave O. and I have talked about this in reference to the Arch Coordination WG.  We're finding - surprise surprise - that neither of us feel like we have the time to properly run the group, which is the initial implementation of the "checklist" - i.e., a group of folks who manually connect ADRs with stakeholders.

**Comment by nedbat** [comment]
Maybe we should close this now, and come back to it when OEP-56 picks up again. @davidjoy?

**Comment by davidjoy** [comment]
If we'd like to clean up the board, sure. It does feel like this effort belongs more squarely in the community than as part of the OSPWG.  Dave, Feanil, and I need to go get our act together.
