### ISSUE TITLE
Write guidelines for public vs private information

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#64]
On Jul 28 we discussed the split of wikis, and that pages were being written in the private wiki that could go into the public wiki.  One concrete step we could take to improve the situation is to explain to people what information can be public, and what information should be private.

**Comment by nsprenkle** [comment]
Made a placeholder page at [2U Confluence > Documentation > Where to put new docs](https://2u-internal.atlassian.net/wiki/spaces/DOC/pages/120586314/2U+or+Open+edX+Where+to+put+new+docs)

**Comment by robrap** [comment]
1. I'm wondering if there is any overlap between this ticket and @feanil's work at designating where documentation should live. I imagine so, if a doc doesn't even belong in the wiki.
2. [food-for-thought] I want to note that many docs (as a whole) don’t fit squarely in one category or the other, although content may. For example, where the wider community needs to know some of the information on a topic, but some is private and/or specific to edX/2U. I’d like there to be a way for public docs to have sections that are clearly designated as being specific to a company, or private links that are clearly designated and help navigate someone to company specific nuances of a topic.

**Comment by nedbat** [comment]
@robrap You are right on both points.

Feanil is crafting new guidance on where information should go, and we have https://2u-internal.atlassian.net/wiki/spaces/DOC/pages/10487507/Documentation+Strategy, which I hope isn't too different from what tCRIL is moving towards.

And absolutely, we have to get good at straddling the private/public line, either by linking between two wikis, or delineating sections.  Sometimes information is private because it is truly confidential, and sometimes it's safe to make public, but uninteresting outside of 2U.

**Comment by nedbat** [comment]
This is stalled, we can re-open if we need to.
