### ISSUE TITLE
Propose a post-split organization for the ENG wiki space

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#69]
Related to #64

**Comment by davidjoy** [comment]
I asked Julia Song about this and she was going to talk to Carla about whether or not we wanted to use ENG for all of TechDev.

**Comment by nedbat** [comment]
If this is about the 2U wiki, then this isn't really an Open Source Process working group concern.  I have opinions about wiki organization, but I'm going to close this here.  Feel free to link to some other tracker that is following this question.
