### ISSUE TITLE
Document how to transfer a repo from edx to openedx

### ISSUE THREAD

**Issue by nedbat** [edx/open-source-process-wg#78]
See https://github.com/openedx/tcril-engineering/issues/467 for questions to answer.

**Comment by feanil** [comment]
Is this sufficient?: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438903337/On-call+Playbooks#%F0%9F%8F%97-Transferring-repositories-into-openedx

**Comment by nedbat** [comment]
What else needs to be said beyond Feanil's wiki page?

**Comment by nedbat** [comment]
The relevant section there is long enough that it makes sense as its own page.  I'm also not sure who the reader is?  The page is an oncall runbook, so the reader is a tCRIL person? But we need directions for 2U people.

We could also add steps there to update READMEs to make sure they are correct (for example, whether contributions are accepted, what security email to use, etc.)

**Comment by nedbat** [comment]
Another write-up: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3241640370/tCRIL+Engineering+Team#%F0%9F%8F%97-Adding-or-removing-repositories-from-the-openedx-GitHub-organization

**Comment by jristau1984** [comment]
@nedbat thoughts on this draft? https://2u-internal.atlassian.net/wiki/spaces/~60ba5f9548549e0069510f53/pages/371818573/How+To+Transfer+an+edx+repo+to+the+openedx+org

**Comment by nedbat** [comment]
I like it! I made a few edits. Let's move it to the Engineering space (as a child here: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19465763/Engineering+Processes), and say this is done.

**Comment by jristau1984** [comment]
Moved: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/371818573/How+To+Transfer+an+edx+repo+to+the+openedx+org
