### ISSUE TITLE
Participate in Phase 2 of Maintainershop Pilot (OEP-55)

### ISSUE THREAD

**Issue by hurtstotouchfire** [edx/open-source-process-wg#80]
[OSPwg Internal Status Page](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/179306499/Project+Maintainers) 

- [x] Identify repos and teams to participate in Phase 2
- [ ] Kick off Public Workstreams Pilot
- [ ] Support teams in meeting Phase 2 requirements
- [ ] https://github.com/edx/open-source-process-wg/issues/72

Phase 1 cleanup:
- [ ] Work with community to get clearer how-to's for Phase 1 tasks
- [ ] Message out to non-participating teams about Phase 1 tasks

**Comment by nedbat** [comment]
Some process improvements:
- https://openedx.atlassian.net/wiki/spaces/COMM/pages/3739910145
- https://openedx.atlassian.net/wiki/spaces/COMM/pages/3695181836

**Comment by nedbat** [comment]
One last item: Ned is chasing down three "No" entries for requirements bots on MFEs: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3663233055/Cumulative+Maintainer+Responsibilities

**Comment by nedbat** [comment]
Phase 2 closed last week.
