### ISSUE TITLE
Document what is needed to get a feature included in an Open edX release

### ISSUE THREAD

**Issue by jristau1984** [edx/open-source-process-wg#84]
T&L wants to get the new Text Editor into the Olive Open edX release.  What is needed to get this done?  Kyle informed us that there is no documented set of steps/requirements at this time.  In our work to get our editor in, we will document what is needed to be done for future reference.

**Comment by nedbat** [comment]
(link to oep-57, mfe reqs, etc)

**Comment by nedbat** [comment]
The new Text Editor is in Olive now.

**Comment by nedbat** [comment]
Things to get covered:
- GitHub org requirement
- Feature flags?
- Tutor settings

**Comment by nedbat** [comment]
@arbrandes is this information in a concise form now?

**Comment by arbrandes** [comment]
@nedbat, @jristau1984, [this](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE) is what we used for Olive (with a corresponding [matrix](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3571056752/Olive+MFE+Candidate+Requirements+Matrix)).

**Comment by nedbat** [comment]
@jristau1984 Can we clarify what precisely we are asking for?  Is this something Open edX Product would need to specify?

**Comment by jristau1984** [comment]
I think this is enough for the moment, and this can probably be closed... https://openedx.atlassian.net/wiki/spaces/COMM/pages/1331268879/Open+edX+Release+FAQ#What-is-included-in-an-Open-edX-release%3F
