### ISSUE TITLE
Don't run the Open edX CLA checker on the `edx` GitHub org

### ISSUE THREAD

**Issue by feanil** [edx/open-source-process-wg#93]
See https://github.com/openedx/tcril-engineering/issues/533 or @nedbat for more details but it's probably a good idea to not run the CLA check in the `edx` org.

**Comment by nedbat** [comment]
Related: #101

**Comment by nedbat** [comment]
Possible: refuse all outside contributions, and fix where needed.

**Comment by nedbat** [comment]
We are updating the bot to be clear that no contributions are accepted: https://github.com/openedx/openedx-webhooks/pull/229

**Comment by nedbat** [comment]
This has been deployed and announced.
